[package]
name = "emergent-drawing"
version = "0.1.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
bitflags = "1.1.0"
