[package]
name = "emergent-presenter"
version = "0.1.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[dependencies]
emergent-drawing = { path = "../drawing" }
emergent-presentation = { path = "../presentation" }
emergent-ui = { path = "../ui" }
log = "0.4.8"