name: Rust
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        rust: [beta, nightly]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true

    - name: Install Ninja (needed for shaderc-sys)
      run: |
        choco install ninja
      if: runner.os == 'Windows'

    - name: Ninja --version
      run: |
        ninja --version
      if: runner.os == 'Windows'

    - name: Build
      run: cargo build -vv --release

    - name: Run Tests
      run: cargo test -vv --release

  rustfmt:
    name: Check Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
      - name: Install Rust
        run: rustup update stable && rustup default stable && rustup component add rustfmt
      - run: cargo fmt -- --check
