[package]
name = "emergent-view"
version = "0.1.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2018"

[dependencies]
emergent-drawing = { path = "../drawing" }
emergent-ui = { path = "../ui" }
emergent-presenter = { path = "../presenter" }
